name: rrad_otp_client
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/rrad-bd/rrad_otp_client_flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
