name: rrad_otp_client
description: Otp client for rrad otp.
version: 0.0.1
homepage: https://github.com/rrad-bd/rrad_otp_client_flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
